/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafoa;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author KelvinCi
 */
public class IguardarInfo extends javax.swing.JFrame {

    /**
     * Creates new form IguardarInfo
     */
    public IguardarInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldname = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rute = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenido = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldnameActionPerformed(evt);
            }
        });
        getContentPane().add(fieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 115, -1));

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 115, 50));

        jLabel1.setText("Nombre de la carpeta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        rute.setText("C:\\Users\\lenovo\\OneDrive\\Documentos");
        getContentPane().add(rute, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 10, 20));

        jLabel2.setText("Contenido a agregar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, 30));

        jLabel3.setText("1)Ingresar el nombre de la carpeta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 280, 30));

        jLabel4.setText("2)Ingresar el contenido en \"Contenido a agregar\"");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, -1));

        jLabel5.setText("3) Presiona \"Guardar\" para guardar los cambios");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 310, -1));

        jLabel6.setText("INSTRUCCIONES:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        contenido.setColumns(20);
        contenido.setRows(5);
        jScrollPane1.setViewportView(contenido);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 130, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldnameActionPerformed
    public static void CrearArchivo(String name, String ruta) {
//        String filename = JOptionPane.showInputDialog("Ingresa el nombre del archivo: ");
        File archivo;

        try {
            archivo = new File(ruta, name + ".txt");
            if (archivo.createNewFile()) {
                JOptionPane.showMessageDialog(null, "Se ha creado correctamente");
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "No se ha podido crear el archivo");

        }
    }

    public static void escribirEntxt(String contenido, String ruta) {

        try {
            PrintWriter escritor = new PrintWriter(new FileWriter(ruta, true));
            escritor.println(contenido);
            escritor.close();
            JOptionPane.showMessageDialog(null, "Se ha escrito correctamente el mensaje");

        } catch (IOException e) {
            String mensaje = "Hubo un error: " + e.getMessage();
            JOptionPane.showMessageDialog(null, mensaje);
        }
    }
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        if (!fieldname.getText().isEmpty() || !contenido.getText().isEmpty()) {
            CrearArchivo(fieldname.getText(), rute.getText());
            String contenidoCondirec = rute.getText() + "\\" + fieldname.getText() + ".txt";
            escribirEntxt(contenido.getText(), contenidoCondirec);
            this.setVisible(false);
            Inicio nueva = new Inicio();
            nueva.setVisible(true);
            nueva.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(null, "No puede haber espacios en blanco");

        }

    }//GEN-LAST:event_guardarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contenido;
    private javax.swing.JTextField fieldname;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField rute;
    // End of variables declaration//GEN-END:variables
}
